### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/yuriem/.local/lib/python3.9/site-packages/pyBigWig.cpython-39-x86_64-linux-gnu.so)

### ISSUE THREAD

**Issue by imendes93** [TheJacksonLaboratory/splicing-pipelines-nf#336]
Possibly fix this issue

```bash
Command error:
 Traceback (most recent call last):
  File "/opt/conda/envs/splicing-pipelines-nf/bin/bamCoverage", line 5, in <module>
   from deeptools.bamCoverage import main
  File "/opt/conda/envs/splicing-pipelines-nf/lib/python3.9/site-packages/deeptools/bamCoverage.py", line 8, in <module>
   from deeptools import writeBedGraph # This should be made directly into a bigWig
  File "/opt/conda/envs/splicing-pipelines-nf/lib/python3.9/site-packages/deeptools/writeBedGraph.py", line 5, in <module>
   import pyBigWig
 ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/yuriem/.local/lib/python3.9/site-packages/pyBigWig.cpython-39-x86_64-linux-gnu.so)
```

**Comment by angarb** [comment]
Christina and I tried:
1) Changing permissions on the singularity cache at  "/projects/anczukow-lab/.singularity_cache/"
2) Adding `--singularity_cache . \` to the main.pbs (This did not seem to overwrite the Sumner config!)
3) Changing the cacheDir in the Sumner config to "./.singularity_cache/"

This did not fix the error above.

**Comment by angarb** [comment]
@cgpu - what were the action items for this problem?
1) Rebuild container 2) Add GLIB to container 3) Soemthing else?

**Comment by marina-yurieva** [comment]
Christina and I had a debugging session - we were able to get inside the container and reproduce the error.

Singularity anczukowlab-splicing-pipelines-nf-3.0.img:/projects/anczukow-lab/yuriem/splicing_pipeline/splicing-pipelines-nf/work/6b/b497c8d890017cbc15b297d720b253> bamCoverage -b SRR4238359.Aligned.sortedByCoord.out.bam -o SRR4238359.bw 
Traceback (most recent call last):
  File "/opt/conda/envs/splicing-pipelines-nf/bin/bamCoverage", line 5, in <module>
    from deeptools.bamCoverage import main
  File "/opt/conda/envs/splicing-pipelines-nf/lib/python3.9/site-packages/deeptools/bamCoverage.py", line 8, in <module>
    from deeptools import writeBedGraph  # This should be made directly into a bigWig
  File "/opt/conda/envs/splicing-pipelines-nf/lib/python3.9/site-packages/deeptools/writeBedGraph.py", line 5, in <module>
    import pyBigWig
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/yuriem/.local/lib/python3.9/site-packages/pyBigWig.cpython-39-x86_64-linux-gnu.so)

```
which bamCoverage
/opt/conda/envs/splicing-pipelines-nf/bin/bamCoverage
```

```
which deeptools
/opt/conda/envs/splicing-pipelines-nf/bin/deeptools
```

**Comment by marina-yurieva** [comment]
Christina and I had a debugging session - we were able to get inside the container and reproduce the error.

Singularity anczukowlab-splicing-pipelines-nf-3.0.img:/projects/anczukow-lab/yuriem/splicing_pipeline/splicing-pipelines-nf/work/6b/b497c8d890017cbc15b297d720b253> bamCoverage -b SRR4238359.Aligned.sortedByCoord.out.bam -o SRR4238359.bw 
Traceback (most recent call last):
  File "/opt/conda/envs/splicing-pipelines-nf/bin/bamCoverage", line 5, in <module>
    from deeptools.bamCoverage import main
  File "/opt/conda/envs/splicing-pipelines-nf/lib/python3.9/site-packages/deeptools/bamCoverage.py", line 8, in <module>
    from deeptools import writeBedGraph  # This should be made directly into a bigWig
  File "/opt/conda/envs/splicing-pipelines-nf/lib/python3.9/site-packages/deeptools/writeBedGraph.py", line 5, in <module>
    import pyBigWig
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/yuriem/.local/lib/python3.9/site-packages/pyBigWig.cpython-39-x86_64-linux-gnu.so)

```
which bamCoverage
/opt/conda/envs/splicing-pipelines-nf/bin/bamCoverage
```

```
which deeptools
/opt/conda/envs/splicing-pipelines-nf/bin/deeptools
```
